# Scheduler AMQP settings
amqp:
    url: amqps://xoilebqg:Nx46t4t9cxQ2M0rF2rIyZPS_xbAhmJIG@hornet.rmq.cloudamqp.com/xoilebqg

exchange:
    name: broadcast
    mode: fanout
    options:
        durable: false
        
message:
    type: object
    required:
        - id
        - listener
        - timeout
    properties:
        id:
          type: number
        listener:
          type: number
        timeout:
          type: number  
          
