
amqp:
    url: amqps://xoilebqg:Nx46t4t9cxQ2M0rF2rIyZPS_xbAhmJIG@hornet.rmq.cloudamqp.com/xoilebqg

exchange:
    name: concentrator
    mode: fanout
        
message:
    type: object
    required:
        - id
        - producer
        - timeout
    properties:
        id:
          type: number
        producer:
          type: number
        timeout:
          type: number  
          
